# Generated by Django 5.2.6 on 2025-11-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251030_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='IProtectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_names', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('initials', models.CharField(blank=True, max_length=255, null=True)),
                ('email_eigen', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_ns', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(choices=[('iProtect', 'iProtect'), ('iWork', 'iWork'), ('OCMS', 'OCMS')], max_length=8)),
                ('had_ad', models.BooleanField(default=False)),
                ('is_in_mail_dist', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IWorkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_names', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('initials', models.CharField(blank=True, max_length=255, null=True)),
                ('email_eigen', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_ns', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(choices=[('iProtect', 'iProtect'), ('iWork', 'iWork'), ('OCMS', 'OCMS')], max_length=8)),
                ('had_ad', models.BooleanField(default=False)),
                ('is_in_mail_dist', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_names', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('initials', models.CharField(blank=True, max_length=255, null=True)),
                ('email_eigen', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_ns', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(choices=[('iProtect', 'iProtect'), ('iWork', 'iWork'), ('OCMS', 'OCMS')], max_length=8)),
                ('had_ad', models.BooleanField(default=False)),
                ('is_in_mail_dist', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
