# Generated by Django 5.2.6 on 2025-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_iprotectuser_iworkuser_ocmsuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iprotectuser',
            old_name='had_ad',
            new_name='has_ad',
        ),
        migrations.RenameField(
            model_name='iworkuser',
            old_name='had_ad',
            new_name='has_ad',
        ),
        migrations.RenameField(
            model_name='ocmsuser',
            old_name='had_ad',
            new_name='has_ad',
        ),
        migrations.AddField(
            model_name='iprotectuser',
            name='ad_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iprotectuser',
            name='email_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iworkuser',
            name='ad_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iworkuser',
            name='email_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocmsuser',
            name='ad_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocmsuser',
            name='email_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
