# Generated by Django 5.2.6 on 2025-11-28 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_weightmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightmeasurement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weight_measurements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
