# Generated by Django 5.2.6 on 2025-12-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_weightmeasurement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprotectuser',
            name='inlog_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iworkuser',
            name='inlog_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocmsuser',
            name='inlog_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
