# Generated by Django 5.2.6 on 2026-04-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(choices=[('iprotect', 'iProtect'), ('iwork', 'iWork'), ('ocms', 'OCMS')], max_length=20)),
                ('source', models.CharField(choices=[('users', 'Users'), ('mail_dist_list', 'Mail Distribution List'), ('ad_group', 'AD Group')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(choices=[('iprotect', 'iProtect'), ('iwork', 'iWork'), ('ocms', 'OCMS')], max_length=20)),
                ('source', models.CharField(choices=[('users', 'Users'), ('mail_dist_list', 'Mail Distribution List'), ('ad_group', 'AD Group')], max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['username'],
                'indexes': [models.Index(fields=['application', 'source'], name='identity_ch_applica_72a11e_idx')],
                'unique_together': {('application', 'source', 'username')},
            },
        ),
    ]
